# docker-compose.prod.yml (for production on VPS)

services:
  web:
    # Production settings
    environment:
      - API_DEBUG=false
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  monitor:
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Production crawler settings (runs automatically)
  crawler:
    environment:
      - SCAN_MODE=slow # Use slow mode for production (respectful crawling)
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: cdon-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - cdon-net
    profiles:
      - production
