# docker-compose.override.yml (for development with Podman)

services:
  web:
    # Development-specific settings
    environment:
      - API_DEBUG=true
      - API_PORT=8080
    volumes:
      # Mount source code for hot reload in development
      - ./src:/app/src
    # Override command to use src path when volume mounted
    command: python -m cdon_watcher web

  monitor:
    # Shorter interval for testing
    environment:
      - CHECK_INTERVAL_HOURS=1
    volumes:
      # Mount source code for development
      - ./src:/app/src
    # Override command to use src path when volume mounted
    command: python -m cdon_watcher monitor

  crawler:
    # Mount source code for development
    volumes:
      - ./src:/app/src
    # Override command to use src path when volume mounted
    command: python -m cdon_watcher crawl
    # Prevent crawler from running automatically in development
    profiles:
      - crawler
