# docker-compose.override.yml (for development with Podman)
version: '3.8'

services:
  web:
    # Development-specific settings
    environment:
      - FLASK_DEBUG=true
      - FLASK_PORT=8080
    volumes:
      # Mount source code for hot reload in development
      - ./cdon_scraper.py:/app/cdon_scraper.py
      - ./monitor.py:/app/monitor.py
    
  monitor:
    # Shorter interval for testing
    environment:
      - CHECK_INTERVAL_HOURS=1

  crawler:
    # Mount source code for development
    volumes:
      - ./cdon_scraper.py:/app/cdon_scraper.py
      - ./monitor.py:/app/monitor.py
