# docker-compose.yml

services:
  # Web dashboard service
  web:
    build:
      context: .
      dockerfile: Dockerfile.base
    container_name: cdon-web
    ports:
      - '8080:8080'
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - SERVICE_MODE=web
      - DB_PATH=/app/data/cdon_movies.db
      - POSTER_DIR=/app/data/posters
      - TMDB_API_KEY=${TMDB_API_KEY:-}
      - TZ=Europe/Helsinki
      - PYTHONPATH=/app
    command: python -m cdon_watcher web
    restart: unless-stopped
    networks:
      - cdon-net

  # Price monitor service (runs periodically)
  monitor:
    build:
      context: .
      dockerfile: Dockerfile.base
    container_name: cdon-monitor
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - SERVICE_MODE=monitor
      - DB_PATH=/app/data/cdon_movies.db
      - POSTER_DIR=/app/data/posters
      - TMDB_API_KEY=${TMDB_API_KEY:-}
      - CHECK_INTERVAL_HOURS=6
      - TZ=Europe/Helsinki
      - PYTHONPATH=/app
      # Email configuration (optional)
      - EMAIL_ENABLED=false
      - EMAIL_FROM=${EMAIL_FROM:-}
      - EMAIL_TO=${EMAIL_TO:-}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-}
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      # Discord webhook (optional)
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK:-}
    command: python -m cdon_watcher monitor
    restart: unless-stopped
    depends_on:
      - web
    networks:
      - cdon-net

  # One-time crawler (use for initial setup or manual runs)
  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    container_name: cdon-crawler
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - SERVICE_MODE=crawl
      - DB_PATH=/app/data/cdon_movies.db
      - POSTER_DIR=/app/data/posters
      - TMDB_API_KEY=${TMDB_API_KEY:-}
      - MAX_PAGES_PER_CATEGORY=${MAX_PAGES_PER_CATEGORY:-10}
      - TZ=Europe/Helsinki
      - PYTHONPATH=/app
      - PLAYWRIGHT_BROWSERS_PATH=/app/playwright_browsers
    command: python -m cdon_watcher crawl
    networks:
      - cdon-net

networks:
  cdon-net:
    driver: bridge

volumes:
  data:
    driver: local
